### ISSUE TITLE
hyp link: TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by danstarns** [hypermodeinc/hyp-cli#51]
I am getting an error `TypeError: Cannot read properties of undefined (reading 'replace')` when linking the default project with the instructions listed in the UI. I followed the installing modus guide, then created the project using `modus new` and when trying `modus link` it threw the type error.

- Node v: `v22.4.1`
- Hypermode CLI `v0.1.7`
- Source https://github.com/danstarns/gqlpt-modus (unchanged from `modus new`)

The screenshot shows the instructions I followed(success in green), including successfully linking the project but failing in red with the type error. 

<img width="1296" alt="Screenshot 2024-11-21 at 19 57 12" src="https://github.com/user-attachments/assets/43de8028-51f7-439c-8be0-5a67894e94ce">
<img width="1296" alt="Screenshot_2024-11-21_at_19 49 31" src="https://github.com/user-attachments/assets/7c35ca40-af0e-45bc-a28a-fec539fc6c62">

**Comment by danstarns** [comment]
Update I used DEBUG to run `hyp link`, here is the output: 

```
gqlpt-modus git:(main) DEBUG=* hyp link
  oclif:main process.execPath: /Users/danielstarns/.nvm/versions/node/v22.4.1/bin/node +0ms
  oclif:main process.execArgv:  +1ms
  oclif:main process.argv: [
  oclif:main   '/Users/danielstarns/.nvm/versions/node/v22.4.1/bin/node',
  oclif:main   '/Users/danielstarns/.hypermode/cli/bin/hyp',
  oclif:main   'link'
  oclif:main ] +0ms
  oclif:find-root:root-plugin Finding root plugin using /Users/danielstarns/.hypermode/cli/bin/run.js +0ms
  oclif:find-root:root-plugin Finding root starting at /Users/danielstarns/.hypermode/cli/bin/run.js +0ms
  oclif:find-root:root-plugin Checking /Users/danielstarns/.hypermode/cli/bin/package.json +0ms
  oclif:find-root:root-plugin Checking /Users/danielstarns/.hypermode/cli/package.json +1ms
  oclif:find-root:root-plugin Found root by traversing up from starting point! +0ms
  oclif:find-root:root-plugin Found root at /Users/danielstarns/.hypermode/cli +0ms
  oclif:config loading core plugin from /Users/danielstarns/.hypermode/cli +0ms
  oclif:read-pjson found oclif config in /Users/danielstarns/.hypermode/cli/package.json +0ms
  oclif:config:@hypermode/hyp-cli command discovery options {
  globPatterns: [
    '**/*.+(js|cjs|mjs|ts|tsx|mts|cts)',
    '!**/*.+(d.ts|test.ts|test.js|spec.ts|spec.js|d.mts|d.cts)?(x)'
  ],
  strategy: 'pattern',
  target: './dist/commands'
} +0ms
  oclif:config:@hypermode/hyp-cli using manifest from /Users/danielstarns/.hypermode/cli/oclif.manifest.json +0ms
  oclif:config reading user plugins pjson /Users/danielstarns/.local/share/hyp/package.json +8ms
  oclif:config config done +0ms
  oclif:config start init hook +1ms
  oclif:config init hook done +0ms
  oclif:config runCommand link [] +0ms
  oclif:config:ts-path Skipping typescript path lookup for /Users/danielstarns/.hypermode/cli because NODE_ENV is NOT "test" or "development" +0ms
  oclif:config:@hypermode/hyp-cli (import) /Users/danielstarns/.hypermode/cli/dist/commands/link/index.js +36ms
  oclif:config start prerun hook +27ms
  oclif:config prerun hook done +0ms
  oclif:hyp:link init version: @oclif/core@4.0.33 argv: [] +0ms
    TypeError: Cannot read properties of undefined (reading 'replace')
  oclif:error TypeError: Cannot read properties of undefined (reading 'replace')
  oclif:error     at LinkIndex.run (file://~/.hypermode/cli/dist/commands/link/index.js:108:46)
  oclif:error     at async LinkIndex._run (~/.hypermode/cli/node_modules/@oclif/core/lib/command.js:302:22)
  oclif:error     at async Config.runCommand (~/.hypermode/cli/node_modules/@oclif/core/lib/config/config.js:425:25)
  oclif:error     at async run (~/.hypermode/cli/node_modules/@oclif/core/lib/main.js:95:16)
  oclif:error     at async file://~/.hypermode/cli/bin/run.js:5:1 +0ms
```

**Comment by danstarns** [comment]
Update it was because my remote is `ssh` not HTTP. 

I replaced to HTTP and it worked: 

```diff
[core]
    repositoryformatversion = 0
    filemode = true
    bare = false
    logallrefupdates = true
    ignorecase = true
    precomposeunicode = true
[remote "origin"]
-   url = git@github.com:danstarns/gqlpt-modus.git
+   url = https://github.com/danstarns/gqlpt-modus.git
    fetch = +refs/heads/*:refs/remotes/origin/*
```
